### ISSUE TITLE
Style the input field for in-directory searching.

### ISSUE THREAD

**Issue by alligatortower** [tkem/mopidy-mobile#114]
Left a rating on your app, you asked me to leave an issue.

Currently the input appears as blank white space indistinguishable from the background, to the right of the search type choice drop down. I think there should be some styling indicating the query input field. Perhaps some placeholder text? Honestly, it probably deserves its own line entirely

Expanding on that, the disabled red "cancel" circle and green "add" circle are confusing. The green circle appears next to "find exact" which would imply that it relates to "find exact."  I think instead, the red circle should not appear until you have added an extra type field (minimum two dropdowns) and be hidden otherwise. The add circle might deserve it's own line, maybe in smaller size, centered below the bottom-most type dropdown line?

If I'm not articulating this well enough I can try to mock something up visually.

**Comment by tkem** [comment]
Thanks for reporting! I'm also not quite happy with the look of the query view myself, but I'm a firm believer if "form follows function", so I decided to get this out quickly.
As for the input field being indistinguishable from background, you're absolutely right. The easiest way to improve this short-term would indeed be a placeholder, I suppose. I'll try to get this into an update ASAP. As for putting the text input in its own line, I'm not quite sure; I actually like how search jets and values line up right now. Are you having problems with the layout if thus, for example wrapping on smaller phone?
As for the plus and minus buttons, I was considering moving the " add" button to the navigation bar, since I see the problem with putting it next to the exact box. Any thoughts on that?

**Comment by alligatortower** [comment]
I think that's all fine, yeah

**Comment by tkem** [comment]
Another approach I just saw using Google Contacts would be to show another input field as soon as you actually type something into the first one. This would let me get rid of the "add" button altogether - moving this to the nav-bar might not be that intuitive after all.
Contacts also displays an "x" to the right of the input only if it contains some text. This may also be more intuitive for the user.
