### ISSUE TITLE
Search results don't show album artists

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#119]
Typo: `album.artist` -> `album.artists`

**Comment by F74** [comment]
I have the following mopidy.conf, but Album, Artis and other dosn't work.
With this configuration other client musicbox_webclient or mobile display the list of the artists, or albums coorectly.

If i change  Albums local:directory?type=album  --> Albums local:directory?type=albums

after mopidy service restarted artist don't work with other clients.

[moped]
enabled = true

[local-sqlite]
enabled = true

# top-level directories for browsing, as <name> <uri>
directories =
    Folders                 local:directory:
    Albums                  local:directory?type=album
    Artists                 local:directory?type=artist
    Composers               local:directory?type=artist&role=composer
    Genres                  local:directory?type=genre
    Performers              local:directory?type=artist&role=performer
    Release Years           local:directory?type=date&format=%25Y
    Tracks                  local:directory?type=track
    Last Week's Updates     local:directory?max-age=604800
    Last Month's Updates    local:directory?max-age=2592000

# database connection timeout in seconds
timeout = 15

# whether to use an album's musicbrainz_id for generating its URI
use_album_mbid_uri = true

# whether to use an artist's musicbrainz_id for generating its URI;
# disabled by default, since some taggers do not handle this well for
# multi-artist tracks [https://github.com/sampsyo/beets/issues/907]
use_artist_mbid_uri = false

# override search limit provided by Mopidy core; set to -1 (no limit)
# to emulate current behavior of json library
# [https://github.com/mopidy/mopidy/issues/917]
search_limit = -1

**Comment by tkem** [comment]
I don't think this is related in any way to mopidy-mobile. 

If you think this is an issue with mopidy-local-sqlite (though I doubt that, since you're changing the config in arbitrary, non-documented ways), please open an issue for this at https://github.com/mopidy/mopidy-local-sqlite/issues.
