### ISSUE TITLE
Allow reordering of entries in the playlist

### ISSUE THREAD

**Issue by ZenithDK** [tkem/mopidy-mobile#178]
It's really nice to be able to reorder the entries in the playlist. I wonder if this could be done by having a small up/down indicator at the left of the album art?

Or something like MPDroid has here: http://blogs.fsfe.org/mk/files/2014/02/ilovefs-mpddroid-small.png

**Comment by tkem** [comment]
Nice idea! Currently, reordering is based on what Ionic (the framework on which MoMo builds) provides OOTB. Since my resources are limited, I'd rather keep it that way, unless there's new functionality provided by the framework or a plugin. Will keep this open as a reminder, though. Thanks for sharing, anyway!

**Comment by tkem** [comment]
And, as always, contributions (PRs) are welcome, of course ;-)

**Comment by tkem** [comment]
Just to make sure I didn't get you wrong - you *do* know about MoMo's current list edit features (pen icon), don't you?

**Comment by martinanton** [comment]
this features are realy great!...thanks very much!

**Comment by tkem** [comment]
Plans are to switch to more "seamless" drag'n'drop for reordering items, i.e. getting rid of "edit" mode, but that's probably not what the OP had in mind.
