### ISSUE TITLE
Show track and disc number in track info dialog

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#196]
These have simply been overlooked but might be useful, for example for checking track order as returned by a backend.
@slimer: Could you provide Spanish and Catalan translations for "Track number" and "Disc number" to be shown in the track info dialog?

**Comment by slimer** [comment]
Spanish:
Track Number = Número de Pista (Shorter N° de Pista)
Disc Number: Número de Disco (N° de Disco)

Catalan:
Track Number: Idem as Spanish.
Disc Number: Numero de Disc (N° de Disc)

Sorry. I'm late because I'm on holidays, disconnected.  ;-)
El dia 03/05/2016 07:56, "Thomas Kemmer" <notifications@github.com> va
escriure:

These have simply been overlooked but might be useful, for example for
checking track order as returned by a backend.
@slimer <https://github.com/slimer>: Could you provide Spanish and Catalan
translations for "Track number" and "Disc number" to be shown in the track
info dialog?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/tkem/mopidy-mobile/issues/196>

**Comment by tkem** [comment]
Thanks! Don't worry, will take some time before I get to it, anyway. Have a nice holiday!
