### ISSUE TITLE
Change step of Android hardware volume keys

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-mobile#204]
Change to +/- 5 or make configurable. +/- 10 seems too much.

**Comment by alexjaw** [comment]
I think that this is a great idea. I'm actually trying to see whats going on in the javascript when volume is changed. I would like to enhance the volume slider so that its easy to make small volume increments with the same slider. One possibility: incremental volume adjustments (by a fixed value) when user taps anywhere on the slider. As its now you really have to be very carefull with the slider if you want small adjustments. This means that if user wants large volume change, he must grab the volume and "drag" it to the required volume level. Fine adjustements around the volume level are done just by tapping anywhere on the slider. 

I haven't figured out:

1.  How to get the present volume level, i.e. before the tap on the volume slider
2. How to diffrentiate between slider events: one event is a tap and relaese. The other event (larger volume adjustments) is tap - move - release.

**Comment by tkem** [comment]
@alexjaw: This issue is about controlling the Android app's volume with hardware volume keys. Title may be misleading, but since I'm the only developer so far, I take shortcuts ;-)
